[tool.poetry]
name = "docstructai"
version = "0.1.0"
description = ""
authors = ["Albert Adams <albeadams@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
